import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  FileText,
  Users,
  Activity,
  Shield,
  CreditCard,
  History,
  AlertTriangle,
  CheckCircle,
  Download,
  BarChart3,
  Calendar,
  TrendingUp
} from "lucide-react";

interface ReportsProps {
  user: { email: string; name?: string };
}

type ReportType = "registration" | "activity" | "filescan" | "malware" | "payment" | "history";

export const Reports = ({ user }: ReportsProps) => {
  const [activeReport, setActiveReport] = useState<ReportType>("registration");

  const reportTabs = [
    { id: "registration" as const, label: "User Registration", icon: Users },
    { id: "activity" as const, label: "User Activity", icon: Activity },
    { id: "filescan" as const, label: "File Scan", icon: FileText },
    { id: "malware" as const, label: "Malware Detection", icon: Shield },
    { id: "payment" as const, label: "Payment", icon: CreditCard },
    { id: "history" as const, label: "Scan History", icon: History },
  ];

  const downloadReport = (reportName: string) => {
    const reportContent = generateReportContent(reportName);
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `HackShield_${reportName}_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateReportContent = (reportName: string) => {
    return `
╔══════════════════════════════════════════════════╗
║         HACKSHIELD - ${reportName.toUpperCase()} REPORT         ║
╠══════════════════════════════════════════════════╣

Generated: ${new Date().toLocaleString()}
Generated By: ${user.name || user.email}
Report Type: ${reportName}

──────────────────────────────────────────────────
                    SUMMARY
──────────────────────────────────────────────────

This report was generated by HackShield AI Malware 
Scanner. All data is encrypted and securely stored.

══════════════════════════════════════════════════
         Powered by HackShield v2.1
══════════════════════════════════════════════════
    `.trim();
  };

  return (
    <div className="space-y-6">
      {/* Report Navigation */}
      <Card className="bg-card/80 border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <BarChart3 className="w-5 h-5" />
            Reports Dashboard
          </CardTitle>
          <CardDescription>View and download detailed security reports</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {reportTabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <Button
                  key={tab.id}
                  variant={activeReport === tab.id ? "cyber" : "cyber-outline"}
                  size="sm"
                  className="justify-start"
                  onClick={() => setActiveReport(tab.id)}
                >
                  <Icon className="w-4 h-4 mr-2 flex-shrink-0" />
                  <span className="truncate text-xs">{tab.label}</span>
                </Button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Report Content */}
      {activeReport === "registration" && <UserRegistrationReport user={user} onDownload={() => downloadReport("User_Registration")} />}
      {activeReport === "activity" && <UserActivityReport user={user} onDownload={() => downloadReport("User_Activity")} />}
      {activeReport === "filescan" && <FileScanReport onDownload={() => downloadReport("File_Scan")} />}
      {activeReport === "malware" && <MalwareDetectionReport onDownload={() => downloadReport("Malware_Detection")} />}
      {activeReport === "payment" && <PaymentReport onDownload={() => downloadReport("Payment")} />}
      {activeReport === "history" && <ScanHistoryReport onDownload={() => downloadReport("Scan_History")} />}
    </div>
  );
};

// Report 1: User Registration Report
const UserRegistrationReport = ({ user, onDownload }: { user: { email: string; name?: string }; onDownload: () => void }) => {
  const registrations = [
    { id: 1, name: "Anuj Sawant", email: "sawantanuj859@gmail.com", date: "2026-03-10", status: "active" },
    { id: 2, name: "Rahul Patil", email: "rahul.patil@gmail.com", date: "2026-03-11", status: "active" },
    { id: 3, name: "Sneha Desai", email: "sneha.desai@yahoo.com", date: "2026-03-12", status: "active" },
    { id: 4, name: "Priya Sharma", email: "priya.sharma@outlook.com", date: "2026-03-13", status: "pending" },
    { id: 5, name: "Amit Kumar", email: "amit.kumar@gmail.com", date: "2026-03-14", status: "active" },
  ];

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <Users className="w-5 h-5" />
            User Registration Report
          </CardTitle>
          <CardDescription>Overview of registered users</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">5</p>
            <p className="text-xs text-muted-foreground">Total Users</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">4</p>
            <p className="text-xs text-muted-foreground">Active</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-warning-amber">1</p>
            <p className="text-xs text-muted-foreground">Pending</p>
          </div>
        </div>
        <div className="space-y-3">
          {registrations.map((reg) => (
            <div key={reg.id} className="flex items-center justify-between p-3 bg-background/50 rounded-lg border border-border">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-cyber-green/20 flex items-center justify-center">
                  <Users className="w-4 h-4 text-cyber-green" />
                </div>
                <div>
                  <p className="text-sm font-medium text-foreground">{reg.name}</p>
                  <p className="text-xs text-muted-foreground">{reg.email}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className="text-xs text-muted-foreground">{reg.date}</span>
                <Badge className={reg.status === "active" ? "bg-cyber-green text-background" : "bg-warning-amber text-background"}>
                  {reg.status}
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

// Report 2: User Activity Report
const UserActivityReport = ({ user, onDownload }: { user: { email: string; name?: string }; onDownload: () => void }) => {
  const activities = [
    { id: 1, action: "File Uploaded", file: "report.pdf", time: "10:30 AM", status: "success" },
    { id: 2, action: "Scan Completed", file: "setup.exe", time: "10:32 AM", status: "warning" },
    { id: 3, action: "Report Downloaded", file: "scan_report.txt", time: "10:35 AM", status: "success" },
    { id: 4, action: "Payment Made", file: "Premium Plan", time: "11:00 AM", status: "success" },
    { id: 5, action: "File Uploaded", file: "script.py", time: "11:15 AM", status: "success" },
    { id: 6, action: "Scan Completed", file: "script.py", time: "11:17 AM", status: "success" },
    { id: 7, action: "Login", file: "sawantanuj859@gmail.com", time: "09:00 AM", status: "success" },
  ];

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <Activity className="w-5 h-5" />
            User Activity Report
          </CardTitle>
          <CardDescription>Recent user activities and actions</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">7</p>
            <p className="text-xs text-muted-foreground">Total Activities</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">Today</p>
            <p className="text-xs text-muted-foreground">Last Active</p>
          </div>
        </div>
        <div className="space-y-3">
          {activities.map((act) => (
            <div key={act.id} className="flex items-center justify-between p-3 bg-background/50 rounded-lg border border-border">
              <div className="flex items-center gap-3">
                <div className={`w-2 h-2 rounded-full ${act.status === "success" ? "bg-cyber-green" : "bg-warning-amber"}`} />
                <div>
                  <p className="text-sm font-medium text-foreground">{act.action}</p>
                  <p className="text-xs text-muted-foreground">{act.file}</p>
                </div>
              </div>
              <span className="text-xs text-muted-foreground font-mono">{act.time}</span>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

// Report 3: File Scan Report
const FileScanReport = ({ onDownload }: { onDownload: () => void }) => {
  const scans = [
    { id: 1, file: "document.pdf", size: "1.2 MB", type: "PDF", result: "safe", confidence: 98.5 },
    { id: 2, file: "setup.exe", size: "4.8 MB", type: "EXE", result: "malware", confidence: 94.7 },
    { id: 3, file: "notes.txt", size: "12 KB", type: "TXT", result: "safe", confidence: 99.1 },
    { id: 4, file: "report.docx", size: "856 KB", type: "DOCX", result: "safe", confidence: 97.3 },
    { id: 5, file: "script.py", size: "4 KB", type: "PY", result: "safe", confidence: 96.8 },
  ];

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <FileText className="w-5 h-5" />
            File Scan Report
          </CardTitle>
          <CardDescription>Detailed file analysis results</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">5</p>
            <p className="text-xs text-muted-foreground">Files Scanned</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">4</p>
            <p className="text-xs text-muted-foreground">Safe</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-danger-red">1</p>
            <p className="text-xs text-muted-foreground">Threats</p>
          </div>
        </div>
        <div className="space-y-3">
          {scans.map((scan) => (
            <div key={scan.id} className="flex items-center justify-between p-3 bg-background/50 rounded-lg border border-border">
              <div className="flex items-center gap-3">
                {scan.result === "safe" ? (
                  <CheckCircle className="w-5 h-5 text-cyber-green" />
                ) : (
                  <AlertTriangle className="w-5 h-5 text-danger-red" />
                )}
                <div>
                  <p className="text-sm font-medium text-foreground">{scan.file}</p>
                  <p className="text-xs text-muted-foreground">{scan.size} • {scan.type}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono text-muted-foreground">{scan.confidence}%</span>
                <Badge className={scan.result === "safe" ? "bg-cyber-green text-background" : "bg-danger-red text-destructive-foreground"}>
                  {scan.result.toUpperCase()}
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

// Report 4: Malware Detection Report
const MalwareDetectionReport = ({ onDownload }: { onDownload: () => void }) => {
  const threats = [
    { id: 1, file: "setup.exe", threat: "Trojan.Generic", severity: "High", engine: "VirusTotal", date: "2026-03-12" },
    { id: 2, file: "crack.exe", threat: "Adware.Downloader", severity: "Medium", engine: "VirusTotal", date: "2026-03-11" },
    { id: 3, file: "keygen.exe", threat: "Backdoor.Agent", severity: "Critical", engine: "VirusTotal", date: "2026-03-10" },
  ];

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <Shield className="w-5 h-5" />
            Malware Detection Report
          </CardTitle>
          <CardDescription>Detected threats and security alerts</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-danger-red">3</p>
            <p className="text-xs text-muted-foreground">Threats Found</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-danger-red">1</p>
            <p className="text-xs text-muted-foreground">Critical</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-warning-amber">1</p>
            <p className="text-xs text-muted-foreground">Medium</p>
          </div>
        </div>
        <div className="space-y-3">
          {threats.map((threat) => (
            <div key={threat.id} className="p-4 bg-danger-red/10 rounded-lg border border-danger-red/30">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-danger-red" />
                  <span className="text-sm font-bold text-foreground">{threat.file}</span>
                </div>
                <Badge className={
                  threat.severity === "Critical" ? "bg-danger-red text-destructive-foreground" :
                  threat.severity === "High" ? "bg-danger-red/80 text-destructive-foreground" :
                  "bg-warning-amber text-background"
                }>
                  {threat.severity}
                </Badge>
              </div>
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span>Threat: <span className="text-danger-red font-mono">{threat.threat}</span></span>
                <span>Engine: {threat.engine}</span>
                <span>{threat.date}</span>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

// Report 5: Payment Report
const PaymentReport = ({ onDownload }: { onDownload: () => void }) => {
  const payments = [
    { id: 1, type: "Single Scan", amount: 199, method: "UPI", status: "success", date: "2026-03-14", txnId: "TXN001234" },
    { id: 2, type: "Premium Monthly", amount: 799, method: "Card", status: "success", date: "2026-03-12", txnId: "TXN001189" },
    { id: 3, type: "Single Scan", amount: 199, method: "UPI", status: "success", date: "2026-03-10", txnId: "TXN001102" },
    { id: 4, type: "Single Scan", amount: 199, method: "Netbanking", status: "failed", date: "2026-03-09", txnId: "TXN001088" },
  ];

  const totalRevenue = payments.filter(p => p.status === "success").reduce((sum, p) => sum + p.amount, 0);

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <CreditCard className="w-5 h-5" />
            Payment Report
          </CardTitle>
          <CardDescription>Transaction history and payment details</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">₹{totalRevenue}</p>
            <p className="text-xs text-muted-foreground">Total Revenue</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">3</p>
            <p className="text-xs text-muted-foreground">Successful</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-danger-red">1</p>
            <p className="text-xs text-muted-foreground">Failed</p>
          </div>
        </div>
        <div className="space-y-3">
          {payments.map((payment) => (
            <div key={payment.id} className="flex items-center justify-between p-3 bg-background/50 rounded-lg border border-border">
              <div className="flex items-center gap-3">
                <CreditCard className={`w-5 h-5 ${payment.status === "success" ? "text-cyber-green" : "text-danger-red"}`} />
                <div>
                  <p className="text-sm font-medium text-foreground">{payment.type}</p>
                  <p className="text-xs text-muted-foreground">{payment.method} • {payment.txnId}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className="text-sm font-bold font-mono text-foreground">₹{payment.amount}</span>
                <Badge className={payment.status === "success" ? "bg-cyber-green text-background" : "bg-danger-red text-destructive-foreground"}>
                  {payment.status}
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

// Report 6: Scan History Report
const ScanHistoryReport = ({ onDownload }: { onDownload: () => void }) => {
  const history = [
    { id: 1, file: "document.pdf", date: "2026-03-14 10:30 AM", duration: "2.3s", result: "safe", confidence: 98.5 },
    { id: 2, file: "setup.exe", date: "2026-03-14 10:32 AM", duration: "4.1s", result: "malware", confidence: 94.7 },
    { id: 3, file: "notes.txt", date: "2026-03-13 02:15 PM", duration: "1.1s", result: "safe", confidence: 99.1 },
    { id: 4, file: "report.docx", date: "2026-03-13 11:45 AM", duration: "2.8s", result: "safe", confidence: 97.3 },
    { id: 5, file: "script.py", date: "2026-03-12 09:20 AM", duration: "1.5s", result: "safe", confidence: 96.8 },
    { id: 6, file: "crack.exe", date: "2026-03-11 04:10 PM", duration: "5.2s", result: "malware", confidence: 92.1 },
  ];

  return (
    <Card className="bg-card/80 border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <History className="w-5 h-5" />
            Scan History Report
          </CardTitle>
          <CardDescription>Complete scanning history with timestamps</CardDescription>
        </div>
        <Button variant="cyber-outline" size="sm" onClick={onDownload}>
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">6</p>
            <p className="text-xs text-muted-foreground">Total Scans</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">2.8s</p>
            <p className="text-xs text-muted-foreground">Avg Duration</p>
          </div>
          <div className="bg-background/50 p-4 rounded-lg border border-border text-center">
            <p className="text-2xl font-bold text-cyber-green">96.4%</p>
            <p className="text-xs text-muted-foreground">Avg Confidence</p>
          </div>
        </div>
        <div className="space-y-3">
          {history.map((item) => (
            <div key={item.id} className="flex items-center justify-between p-3 bg-background/50 rounded-lg border border-border">
              <div className="flex items-center gap-3">
                {item.result === "safe" ? (
                  <CheckCircle className="w-5 h-5 text-cyber-green" />
                ) : (
                  <AlertTriangle className="w-5 h-5 text-danger-red" />
                )}
                <div>
                  <p className="text-sm font-medium text-foreground">{item.file}</p>
                  <p className="text-xs text-muted-foreground">{item.date} • {item.duration}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono text-muted-foreground">{item.confidence}%</span>
                <Badge className={item.result === "safe" ? "bg-cyber-green text-background" : "bg-danger-red text-destructive-foreground"}>
                  {item.result.toUpperCase()}
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};
