import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { 
  Shield, 
  AlertTriangle, 
  CheckCircle, 
  Download, 
  FileText, 
  Clock,
  Zap,
  RotateCcw
} from "lucide-react";

interface ScanResult {
  id: string;
  fileName: string;
  fileSize: number;
  fileType: string;
  status: "safe" | "malware" | "scanning";
  confidence: number;
  scanDate: Date;
  threats?: string[];
}

interface ScanResultsProps {
  scanResult: ScanResult;
  isScanning: boolean;
  onNewScan: () => void;
}

export const ScanResults = ({ scanResult, isScanning, onNewScan }: ScanResultsProps) => {
  const [scanProgress, setScanProgress] = useState(0);
  const [currentPhase, setCurrentPhase] = useState("Initializing...");

  const scanPhases = [
    "Initializing scan engine...",
    "Loading AI models...", 
    "Analyzing file structure...",
    "Checking for known signatures...",
    "Running behavioral analysis...",
    "Calculating threat probability...",
    "Finalizing results..."
  ];

  useEffect(() => {
    if (isScanning) {
      setScanProgress(0);
      setCurrentPhase(scanPhases[0]);
      
      const progressInterval = setInterval(() => {
        setScanProgress(prev => {
          const newProgress = prev + (100 / 50); // Complete in ~5 seconds
          
          // Update phase based on progress
          const phaseIndex = Math.floor((newProgress / 100) * scanPhases.length);
          if (phaseIndex < scanPhases.length) {
            setCurrentPhase(scanPhases[phaseIndex]);
          }
          
          if (newProgress >= 100) {
            clearInterval(progressInterval);
            return 100;
          }
          return newProgress;
        });
      }, 100);

      return () => clearInterval(progressInterval);
    }
  }, [isScanning]);

  const formatFileSize = (bytes: number) => {
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    if (bytes === 0) return '0 Byte';
    const i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)).toString());
    return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];
  };

  const downloadReport = () => {
    // Simulate PDF report generation
    const reportData = {
      fileName: scanResult.fileName,
      scanDate: scanResult.scanDate.toISOString(),
      status: scanResult.status,
      confidence: scanResult.confidence,
      threats: scanResult.threats || []
    };

    const reportContent = `
HackShield Malware Scan Report
==============================

File Information:
- Name: ${reportData.fileName}
- Size: ${formatFileSize(scanResult.fileSize)}
- Type: ${scanResult.fileType.toUpperCase()}
- Scan Date: ${new Date(reportData.scanDate).toLocaleString()}

Scan Results:
- Status: ${reportData.status.toUpperCase()}
- Confidence: ${reportData.confidence}%
- Threats Found: ${reportData.threats.length}

${reportData.threats.length > 0 ? `
Detected Threats:
${reportData.threats.map(threat => `- ${threat}`).join('\n')}
` : ''}

Generated by HackShield AI Malware Scanner
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `HackShield_Report_${scanResult.fileName}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isScanning) {
    return (
      <Card className="bg-card/80 border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-cyber-green">
            <Zap className="w-5 h-5 animate-spin" />
            AI Malware Analysis in Progress
          </CardTitle>
          <CardDescription>
            Advanced machine learning algorithms are analyzing your file
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* File Info */}
          <div className="bg-background/50 rounded-lg p-4 border border-border">
            <div className="flex items-center gap-3 mb-3">
              <FileText className="w-6 h-6 text-cyber-green" />
              <div>
                <p className="font-medium text-foreground">{scanResult.fileName}</p>
                <p className="text-sm text-muted-foreground">
                  {formatFileSize(scanResult.fileSize)} • {scanResult.fileType.toUpperCase()}
                </p>
              </div>
            </div>
          </div>

          {/* Scan Progress */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-foreground">Scan Progress</span>
              <span className="text-sm text-cyber-green font-mono">{Math.round(scanProgress)}%</span>
            </div>
            
            <Progress 
              value={scanProgress} 
              className="h-3 bg-secondary"
            />
            
            <div className="flex items-center gap-2 text-sm text-terminal-green">
              <Clock className="w-4 h-4" />
              <span className="terminal-cursor">{currentPhase}</span>
            </div>
          </div>

          {/* Scanning Animation */}
          <div className="relative bg-background/30 rounded-lg p-8 border border-cyber-green/30">
            <div className="text-center space-y-4">
              <div className="relative mx-auto w-24 h-24">
                <Shield className="w-full h-full text-cyber-green cyber-pulse" />
                <div className="absolute inset-0 border-2 border-cyber-green rounded-full animate-ping opacity-20"></div>
              </div>
              <p className="text-cyber-green font-mono text-lg">SCANNING...</p>
              <div className="w-full h-1 bg-background rounded-full overflow-hidden">
                <div className="h-full bg-gradient-to-r from-cyber-green to-cyber-green-glow scan-animation"></div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Scan completed - show results
  const isSafe = scanResult.status === "safe";
  const statusIcon = isSafe ? CheckCircle : AlertTriangle;
  const statusColor = isSafe ? "text-cyber-green" : "text-danger-red";
  const statusBg = isSafe ? "bg-cyber-green/10" : "bg-danger-red/10";
  const statusBorder = isSafe ? "border-cyber-green/30" : "border-danger-red/30";

  return (
    <div className="space-y-6">
      {/* Main Result Card */}
      <Card className={`${statusBg} ${statusBorder} border-2`}>
        <CardHeader>
          <CardTitle className={`flex items-center gap-3 ${statusColor}`}>
            {React.createElement(statusIcon, { className: "w-8 h-8" })}
            <div>
              <div className="text-2xl font-bold">
                {isSafe ? "✅ FILE IS SAFE" : "⚠️ MALWARE DETECTED"}
              </div>
              <div className="text-sm font-normal text-muted-foreground">
                Analysis completed with {scanResult.confidence}% confidence
              </div>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* File Details */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-background/50 rounded-lg p-4 border border-border">
              <h4 className="text-sm font-medium text-muted-foreground mb-2">File Name</h4>
              <p className="font-mono text-foreground">{scanResult.fileName}</p>
            </div>
            <div className="bg-background/50 rounded-lg p-4 border border-border">
              <h4 className="text-sm font-medium text-muted-foreground mb-2">File Size</h4>
              <p className="font-mono text-foreground">{formatFileSize(scanResult.fileSize)}</p>
            </div>
            <div className="bg-background/50 rounded-lg p-4 border border-border">
              <h4 className="text-sm font-medium text-muted-foreground mb-2">File Type</h4>
              <p className="font-mono text-foreground">{scanResult.fileType.toUpperCase()}</p>
            </div>
          </div>

          {/* Confidence Score */}
          <div className="bg-background/50 rounded-lg p-4 border border-border">
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-sm font-medium text-muted-foreground">Confidence Score</h4>
              <span className={`text-lg font-bold font-mono ${statusColor}`}>
                {scanResult.confidence}%
              </span>
            </div>
            <Progress value={scanResult.confidence} className="h-2" />
          </div>

          {/* Threats Detected */}
          {scanResult.threats && scanResult.threats.length > 0 && (
            <div className="bg-danger-red/10 border border-danger-red/30 rounded-lg p-4">
              <h4 className="text-sm font-medium text-danger-red mb-3 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4" />
                Threats Detected ({scanResult.threats.length})
              </h4>
              <div className="space-y-2">
                {scanResult.threats.map((threat, index) => (
                  <Badge key={index} variant="destructive" className="mr-2 mb-2">
                    {threat}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-3">
            <Button variant="cyber" onClick={downloadReport}>
              <Download className="w-4 h-4 mr-2" />
              Download Report
            </Button>
            <Button variant="cyber-outline" onClick={onNewScan}>
              <RotateCcw className="w-4 h-4 mr-2" />
              Scan Another File
            </Button>
          </div>

          {/* Scan Metadata */}
          <div className="text-xs text-muted-foreground pt-4 border-t border-border">
            <p>Scan ID: {scanResult.id} • Completed: {scanResult.scanDate.toLocaleString()}</p>
            <p className="mt-1">Powered by HackShield AI Malware Detection Engine v2.1</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};